/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package program;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.Timer;
import java.util.Random;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.text.NumberFormat;
import java.util.Locale;

/**
 *
 * @author DAIRA SYAHFITRI
 */
public class ProgramAlatTulis extends javax.swing.JFrame {
    /**
     * Creates new form ProgramAlatTulis
     */
    DefaultTableModel model;
    NumberFormat format = NumberFormat.getCurrencyInstance(new Locale("id", "ID"));

    public ProgramAlatTulis() {
    
     super("Real-Time Clock");
        initComponents();
         addComboBoxKeyListener(); 
                 Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                updateTime();
            }
        });
        timer.start();
            model = new DefaultTableModel();
         int length = 10; // Length of the random string
        String randomString = generateRandomString(length);
        notran.setText(randomString);
        notran.setEnabled(false);
        model.addColumn("Nama Barang");
        model.addColumn("Harga (pack)");
        model.addColumn("Jumlah Beli");
        model.addColumn("Jumlah");
        
        tabel.setModel(model);  
        
            ubyr.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                updateResult();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateResult();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                updateResult();
            }

            private void updateResult() {
                try {
                    double value8 = Double.parseDouble(thrg.getText());
                    double value9 = Double.parseDouble(disk.getText());
                    double value10 = Double.parseDouble(ubyr.getText());
                    
                    double result = value10 - (value8 - value9) ;
                 int resultInteger = (int) result;
                 if( resultInteger >= 0){
                 kbln.setText(String.valueOf(resultInteger));
                        simpan.setEnabled(true);
                 }else{
                    kbln.setText("Uang Gak cukup");   
                 simpan.setEnabled(false);
                 }

                } catch (NumberFormatException ex) {
                         simpan.setEnabled(false);
                    kbln.setText("Uang Gak cukup");
                }
            }
        });
    }
        public static String generateRandomString(int length) {
        String characters = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
        StringBuilder stringBuilder = new StringBuilder();

        Random random = new Random();
        for (int i = 0; i < length; i++) {
            int index = random.nextInt(characters.length());
            char randomChar = characters.charAt(index);
            stringBuilder.append(randomChar);
        }

        return stringBuilder.toString();
    }
        private void updateTime() {
        LocalDateTime now = LocalDateTime.now();

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        String formattedDateTime = now.format(formatter);

        tanggal.setText(formattedDateTime);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        notran = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tanggal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        kdbrg = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        nbrg = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        hbrg = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jbeli = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        simpan = new javax.swing.JButton();
        ttl = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        thrg = new javax.swing.JTextField();
        disk = new javax.swing.JTextField();
        ubyr = new javax.swing.JTextField();
        kbln = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 153, 153));
        jLabel1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel1.setText("Kasir Alat Tulis");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel2.setText("No Transaksi");

        notran.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        notran.setName("textTransaksiNo"); // NOI18N
        notran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notranActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel3.setText("Nama Customer");

        name.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel4.setText("Tanggal");

        tanggal.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        tanggal.setEnabled(false);
        tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggalActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel5.setText("Kode Barang");

        kdbrg.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        kdbrg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A001", "A002", "A003", "A004", "A005", "A006", "A007" }));
        kdbrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kdbrgActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel6.setText("Nama Barang");

        nbrg.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        nbrg.setEnabled(false);
        nbrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbrgActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel7.setText("Harga Barang");

        hbrg.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        hbrg.setEnabled(false);
        hbrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hbrgActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel8.setText("Jumlah Beli (pack)");

        jbeli.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jbeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbeliActionPerformed(evt);
            }
        });

        tabel.setBackground(new java.awt.Color(255, 153, 153));
        tabel.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.setSurrendersFocusOnKeystroke(true);
        jScrollPane1.setViewportView(tabel);

        simpan.setBackground(new java.awt.Color(153, 153, 153));
        simpan.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        simpan.setText("Simpan");
        simpan.setEnabled(false);
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        ttl.setBackground(new java.awt.Color(255, 102, 102));
        ttl.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        ttl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttlActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel9.setText("Total Harga");

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel10.setText("Diskon");

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel11.setText("Uang Bayar");

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel12.setText("Kembalian");

        thrg.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        thrg.setEnabled(false);
        thrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thrgActionPerformed(evt);
            }
        });

        disk.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        disk.setEnabled(false);
        disk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diskActionPerformed(evt);
            }
        });

        ubyr.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        ubyr.setForeground(new java.awt.Color(153, 153, 153));
        ubyr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubyrActionPerformed(evt);
            }
        });

        kbln.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        kbln.setEnabled(false);
        kbln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kblnActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel13.setText("Total  ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ttl, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(thrg, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(ubyr, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(disk, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(kbln))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(simpan)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kdbrg, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nbrg, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hbrg, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbeli, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(name)
                            .addComponent(notran, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(199, 199, 199))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(notran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kdbrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nbrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hbrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(thrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(disk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ubyr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)))
                            .addComponent(simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kbln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ttl, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nbrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nbrgActionPerformed

    private void notranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notranActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_notranActionPerformed
    private void addComboBoxKeyListener() {
       
        kdbrg.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
            
            Object selectedItem = kdbrg.getSelectedItem();
            if(selectedItem == "A001"){
             nbrg.setText("Pensil");
                     hbrg.setText("20000");
            } else if(selectedItem == "A002"){
             nbrg.setText("Penghapus");
                     hbrg.setText("15000");
            } else if (selectedItem == "A003"){
             nbrg.setText("Rautan");
                     hbrg.setText("10000");
            } else if (selectedItem == "A004"){
             nbrg.setText("Pulpen");
                     hbrg.setText("25000");
            } else if (selectedItem == "A005"){
             nbrg.setText("Penggaris");
                     hbrg.setText("14000"); 
            } else if (selectedItem == "A006"){
             nbrg.setText("Buku");
                     hbrg.setText("30000"); 
            } else if (selectedItem == "A007"){
             nbrg.setText("Spidol");
                     hbrg.setText("16000");         
            }         
            }
        });
    }
    private void kdbrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kdbrgActionPerformed
    nbrg.setText("");
    hbrg.setText("");
        // Add more items as neededTODO add your handling code here:
    }//GEN-LAST:event_kdbrgActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void hbrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hbrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hbrgActionPerformed
    public void clearAll(){
        nbrg.setText(""); // First column value
        hbrg.setText(""); // Second column value
        jbeli.setText(""); 
}
    private void tanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalActionPerformed

    private void diskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diskActionPerformed

    private void ubyrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubyrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ubyrActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        System.out.println("        Toko Alat Tulis Dirausa");
        System.out.println("***************************************");
        System.out.println("Jumlah Beli\tBarang           Harga");
        System.out.println("---------------------------------------");
        int rowCount = tabel.getRowCount();
        for (int i = 0; i < rowCount; i++) {
            String barang = tabel.getValueAt(i, 0).toString();
            String harga = tabel.getValueAt(i, 1).toString();
            String jumlah = tabel.getValueAt(i, 2).toString();
            System.out.println(jumlah+ "\t\t" +barang + "        " + harga);
        }
        System.out.println("---------------------------------------");
        System.out.println("Subtotal:\t\t\t " +  ubyr.getText());
        System.out.println("Diskon ("+ "10%):\t\t\t" +  disk.getText());
        System.out.println("---------------------------------------");
        System.out.println("Pembayaran Tunai:\t\t " +  ubyr.getText());
        System.out.println("Kembalian:\t\t\t  " +  kbln.getText());
        System.out.println("\nTanggal dan Jam: " + tanggal.getText());
        System.out.println("***************************************");
        System.out.println("               TERIMAKASIH");        
    }//GEN-LAST:event_simpanActionPerformed

    private void ttlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ttlActionPerformed

    private void kblnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kblnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kblnActionPerformed

    private void jbeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbeliActionPerformed
    tabel.setBackground(new java.awt.Color(255, 204, 204));
        int value5 = Integer.parseInt(hbrg.getText());
        int value6 = Integer.parseInt(jbeli.getText());
        int product = value5 * value6;

    model.addRow(new Object[]{
            nbrg.getText(), // First column value
            hbrg.getText(), // Second column value
            jbeli.getText(), // Third column value
            String.valueOf(product) // Fourth column value (product)
        });
    this.clearAll();
    if(thrg.getText().equals("")){
    thrg.setText(String.valueOf(product));
    }else{
            int currentValue =Integer.parseInt(thrg.getText());
    int productValue = currentValue + product; // Assuming 'product' is the numerical value you want to multiply
    thrg.setText(String.valueOf(productValue));
    }
     
    int value = Integer.parseInt(thrg.getText());
    
    if (value >= 100000) {
        int values =  Integer.parseInt(thrg.getText());
    
    double result =values * 0.1; 
    
    disk.setText(String.valueOf(result));
    } else {
        disk.setText(String.valueOf(0));
    }
       double value8 = Double.parseDouble(thrg.getText());
    double value9 = Double.parseDouble(disk.getText());
    
    int result = (int) (value8 - value9);
    
    ttl.setText( String.valueOf(result));        // TODO add your handling code here:
    }//GEN-LAST:event_jbeliActionPerformed

    private void thrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thrgActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProgramAlatTulis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProgramAlatTulis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProgramAlatTulis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgramAlatTulis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProgramAlatTulis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField disk;
    private javax.swing.JTextField hbrg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jbeli;
    private javax.swing.JTextField kbln;
    private javax.swing.JComboBox<String> kdbrg;
    private javax.swing.JTextField name;
    private javax.swing.JTextField nbrg;
    private javax.swing.JTextField notran;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField tanggal;
    private javax.swing.JTextField thrg;
    private javax.swing.JTextField ttl;
    private javax.swing.JTextField ubyr;
    // End of variables declaration//GEN-END:variables
}